spring:
    datasource:
        url: jdbc:mysql://localhost:3306/erp
        username: root
        password: root
        initialSize: 0
        maxActive: 20
        minIdle: 0
        maxWait: 60000
        validationQuery: SELECT 1
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 25200000
        removeAbandoned: true
        removeAbandonedTimeout: 1800
        logAbandoned: true
        filters: stat
    mybatis:
        aliases: com.github.application.erp.entity
        mapper: com.github.application.erp.repository
---
logging:
    file: /logs/erp.log

---
server:
    port: 8082
    tomcat:
        access_log_enabled: true
        basedir: target/tomcat
---
swagger:
    title: erp API
    description: erp applications and beyond!
    version: 0.0.1
    termsOfServiceUrl: http://github.io/boyley/erp
    contact: 136397156@qq.com
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
